export const TOPIC_SUBTOPICS_MAP: Record<string, Record<string, string[]>> = {
  "DSA": {
    "Searching Algorithms": ["Linear Search", "Binary Search", "Ternary Search"],
    "Sorting Algorithms": ["Bubble Sort", "Selection Sort", "Insertion Sort", "Merge Sort", "Quick Sort", "Heap Sort"],
    "Introduction to Recursion": ["Recursion Basics", "Backtracking", "Divide & Conquer"],
    "Greedy Algorithms": ["Fractional Knapsack", "Huffman Coding", "Activity Selection"],
    "Graph Algorithms": ["BFS & DFS", "Dijkstra's Algorithm", "Kruskal & Prim's Algorithms", "Bellman-Ford & Floyd-Warshall"],
    "Dynamic Programming": ["1D & 2D DP", "Grid DP", "Knapsack DP", "LIS & LCS"],
    "Bitwise Algorithms": ["Bit Operations", "Bit Masking", "Bitwise Hacks"],
    "Segment Tree": ["Range Query & Point Update", "Lazy Propagation"],
    "Binary Indexed Tree": ["Fenwick Tree Basics", "Range Sum Query & Updates"],
    "Trie Data Structure": ["Trie Insertion & Search", "Prefix Matching"],
    "Square Root (Sqrt) Decomposition Algorithm": ["Block Decomposition", "Mo's Algorithm"]
  },
  "Web Development": {
    "HTML": ["Semantic HTML", "Forms & Validation", "Web Storage (Local/Session)"],
    "CSS": ["Flexbox & Grid Layouts", "Responsive Design & Media Queries", "Animations & Transitions"],
    "JavaScript": ["ES6+ Features", "DOM Manipulation", "Async/Await & Promises", "Closures & Scope"],
    "TypeScript": ["Interfaces & Types", "Generics", "TS Configuration"],
    "Git": ["Commits & Branching", "Merging & Rebasing", "Resolving Conflicts"],
    "GitHub": ["Pull Requests & Collaboration", "GitHub Actions CI/CD"],
    "React": ["Component Lifecycle", "Hooks (useState, useEffect, useMemo)", "Context API", "React Performance"],
    "Next.js": ["App Router Routing", "SSR, SSG & ISR", "API Routes & Middleware"],
    "Node.js": ["Event Loop & Event Emitter", "File System (fs) & Path", "Streams & Buffers"],
    "Express.js": ["Routing & Middleware", "Error Handling & Validation"],
    "MongoDB": ["Collections & Documents", "Mongoose Schemas & Models", "Aggregation Pipeline"],
    "PostgreSQL": ["Tables & Relations", "SQL Queries & Joins", "Indexes & Performance"],
    "Prisma": ["Prisma Schema", "Migrations", "Prisma Client CRUD"],
    "REST API": ["HTTP Methods & Status Codes", "Endpoint Design & Versioning"],
    "GraphQL": ["Schemas & Resolvers", "Queries & Mutations", "Apollo Server/Client"],
    "Authentication": ["JWT (JSON Web Tokens)", "Sessions & Cookies", "OAuth 2.0 & Social Logins"],
    "Web Security": ["HTTPS & SSL", "XSS & CSRF Prevention", "CORS & Security Headers"],
    "Tailwind CSS": ["Utility First Concept", "Responsive & State Variants", "Tailwind Config Customization"],
    "Redux": ["Redux Toolkit (RTK)", "Store, Actions & Reducers", "Redux Middleware (Thunk)"],
    "Zustand": ["Zustand Store Creation", "Zustand Persist Middleware"],
    "Docker": ["Containers vs Images", "Dockerfile & Build", "Docker Compose"],
    "Linux": ["Shell & Basic Commands", "File Permissions", "SSH & Keys Setup"],
    "Nginx": ["Reverse Proxy Setup", "Load Balancing", "SSL/TLS Configuration"],
    "AWS": ["EC2 & S3 Basics", "IAM Roles & Security", "AWS Lambda & Serverless"],
    "CI/CD": ["Deployment Pipelines", "GitHub Actions", "Environment Variables Setup"],
    "Testing": ["Jest Unit Testing", "React Testing Library", "Cypress E2E Testing"],
    "WebSockets": ["WebSocket Lifecycle", "Socket.io Integration", "Real-Time Broadcasting"],
    "System Design": ["Caching & Redis", "Database Replication", "Horizontal Scaling"],
    "PWA": ["Service Workers", "Web App Manifest", "Offline Support"],
    "Microservices": ["API Gateway", "Service Discovery", "Event-Driven Architecture", "Message Queues (RabbitMQ/Kafka)"],
    "Serverless": ["FaaS (Functions as a Service)", "Cold Starts & Optimization"],
    "SEO": ["Meta Tags & Structured Data", "Sitemaps & Robots.txt"],
    "Accessibility": ["Semantic Tags & ARIA Roles", "Keyboard Navigation"],
    "Performance Optimization": ["Code Splitting & Lazy Loading", "Core Web Vitals", "Asset Compression"],
    "AI Integration": ["LLM API Calls", "Prompt Engineering basics", "Response Streaming"]
  },
  "App Development": {
    "Programming Fundamentals": ["Control Flow & Loops", "Functions & Scope", "OOP Concepts"],
    "Dart (Flutter) / Kotlin / Swift": ["Dart Basics & Null Safety", "Async programming", "Type systems"],
    "Git": ["Commits & Branching", "Merging & Conflicts"],
    "GitHub": ["PRs & Team Collaboration"],
    "Flutter": ["Widgets Lifecycle", "Stateful vs Stateless Widgets", "Platform Channels"],
    "React Native": ["RN Core Components", "JSX & Styling", "Expo vs Native CLI"],
    "Android Development": ["Activities & Fragments", "XML & Compose Layouts", "Gradle Builds"],
    "iOS Development": ["SwiftUI vs UIKit", "Xcode Storyboards", "Swift Package Manager"],
    "UI/UX Design": ["Wireframing & Prototyping", "Color & Typography Principles"],
    "Material Design": ["Material Principles", "Theme Customization"],
    "Human Interface Guidelines (iOS)": ["Cupertino Layouts", "Navigation Patterns"],
    "State Management": ["BLoC Pattern", "Provider & Riverpod", "React Context/Redux"],
    "Navigation": ["Stack & Tab Navigation", "Deep Linking", "Route Parameters"],
    "Animations": ["Tweens & Controllers", "Hero Transitions", "Lottie Animations"],
    "Local Storage": ["Secure Storage", "Key-Value Storage", "Relational Databases"],
    "SQLite": ["SQLite Open Helper", "SQL CRUD Queries"],
    "Hive": ["Hive Boxes & Adapters", "Type Adapters Setup"],
    "Shared Preferences": ["Key-Value Local Config", "Preferences Helper"],
    "REST API": ["HTTP Client Setup", "JSON Parsing & Serialization", "Error Handling"],
    "GraphQL": ["Apollo Client for App", "Queries & Mutations"],
    "Authentication": ["Firebase Auth", "Biometric Authentication", "JWT Storage"],
    "Firebase": ["Firebase Firestore", "Firebase Cloud Messaging (FCM)", "Firebase Analytics"],
    "Supabase": ["PostgreSQL client", "Supabase Auth & Storage"],
    "Push Notifications": ["APNs Setup (iOS)", "FCM Setup (Android)", "Background Notifications"],
    "Deep Linking": ["Custom URL Schemes", "Universal/App Links"],
    "Maps & Location Services": ["Map Integration", "Geolocation & Tracking", "Geofencing"],
    "Camera": ["Camera Controller", "Image Picker", "QR/Barcode Scanner"],
    "Media Handling": ["Audio Player & Recording", "Video Playback", "Exif Data"],
    "Device Sensors": ["Accelerometer & Gyroscope", "Biometric Scanner Integration"],
    "Background Services": ["WorkManager (Android)", "Background Fetch (iOS)"],
    "Offline First Development": ["Local Caching & Sync", "Conflict Resolution"],
    "Testing": ["Mobile Unit Testing", "Widget/Component Testing", "Integration Testing"],
    "App Security": ["Keychain & Keystore", "Code Obfuscation & ProGuard", "SSL Pinning"],
    "Performance Optimization": ["Image Caching", "Memory Leak Prevention", "Frame Rate Profiling"],
    "CI/CD": ["Fastlane Automation", "App Delivery (TestFlight/Firebase App Dist)"],
    "Play Store Deployment": ["App Bundle Creation", "Google Play Console Releases"],
    "App Store Deployment": ["Xcode Archiving", "App Store Connect Submission"],
    "Analytics": ["Custom Event Tracking", "User Funnel Analysis"],
    "Crash Reporting": ["Crashlytics Integration", "Sentry Error Tracking"],
    "In-App Purchases": ["App Store Billing Setup", "Google Play Billing Setup", "Receipt Validation"],
    "Subscriptions": ["Subscription Lifecycle", "Webhooks Notification"],
    "WebSockets": ["Real-time Sync Connection", "Chat Feature Implementation"],
    "AI Integration": ["On-Device Models (TFLite)", "API calls to OpenAI/Anthropic"],
    "System Design for Mobile Apps": ["Clean Architecture", "Local-Remote Repository Sync"]
  },
  "Machine Learning": {
    "Python": ["Variables & Control Flow", "OOP in Python", "File Handling & Modules"],
    "Mathematics": ["Vectors & Matrices", "Calculus Derivations", "Gradient Descent Optimization"],
    "Statistics": ["Hypothesis Testing & p-values", "Descriptive Statistics", "ANOVA"],
    "Probability": ["Conditional Probability & Bayes", "Probability Distributions"],
    "Linear Algebra": ["Matrix Operations", "Eigenvalues & Eigenvectors", "SVD & PCA"],
    "Calculus": ["Partial Derivatives", "Gradients & Chain Rule"],
    "Data Analysis": ["Data Loading & Inspection", "Grouping & Aggregations"],
    "NumPy": ["NDArrays Creation", "Indexing & Slicing", "Vectorization & Broadcasting"],
    "Pandas": ["Series & DataFrames", "Data Cleaning & Imputation", "Merging & Concatenating"],
    "Data Visualization": ["Matplotlib Basics", "Seaborn Statistical Plots", "Interactive Plots"],
    "Data Cleaning": ["Handling Missing Data", "Outlier Detection & Removal", "Data Types Casting"],
    "Feature Engineering": ["One-Hot & Label Encoding", "Scaling & Normalization", "Creating Interaction Features"],
    "Exploratory Data Analysis (EDA)": ["Correlation Matrix", "Distribution Analysis", "Feature Crossings"],
    "Machine Learning Fundamentals": ["Bias-Variance Tradeoff", "Train-Test Split & Cross-Validation", "Overfitting Prevention"],
    "Supervised Learning": ["Labeled Datasets Concept", "Regression vs Classification"],
    "Unsupervised Learning": ["Unlabeled Datasets Concept", "Clustering & Association"],
    "Regression": ["Linear Regression", "Ridge & Lasso Regularization", "Polynomial Regression"],
    "Classification": ["Logistic Regression", "Decision Trees & Random Forests", "Support Vector Machines (SVM)"],
    "Clustering": ["K-Means Clustering", "DBSCAN Clustering", "Hierarchical Clustering"],
    "Model Evaluation": ["MSE, MAE & R2 (Regression)", "Confusion Matrix & F1-Score (Classify)", "ROC-AUC Curve"],
    "Feature Selection": ["Filter & Wrapper Methods", "L1 Regularization Feature Selection"],
    "Hyperparameter Tuning": ["Grid Search & Random Search", "Bayesian Optimization"],
    "Scikit-Learn": ["Scikit-Learn Estimators", "Pipelines & ColumnTransformers"],
    "Deep Learning": ["Artificial Neurons & Perceptrons", "Activation Functions (ReLU, Sigmoid)", "Backpropagation Algorithm"],
    "Neural Networks": ["Feedforward Networks", "CNNs for Image Processing", "RNNs & LSTMs for Sequences"],
    "TensorFlow": ["TensorFlow Basics & Tensors", "Keras Sequential & Functional API"],
    "PyTorch": ["PyTorch Tensors & Autograd", "Custom Modules (nn.Module)", "Training Loop implementation"],
    "Computer Vision": ["Image Preprocessing & Augmentation", "Object Detection (YOLO)", "Image Segmentation"],
    "Natural Language Processing (NLP)": ["Tokenization & Stop Words", "Word Embeddings (Word2Vec, GloVe)", "BERT & Transformers"],
    "Time Series Analysis": ["ARIMA & SARIMA Models", "LSTM for Time Series Forecasting"],
    "Reinforcement Learning": ["Markov Decision Processes", "Q-Learning & Deep Q-Networks"],
    "MLOps": ["Model Versioning (DVC)", "MLflow Experiment Tracking", "Model Monitoring in Production"],
    "Model Deployment": ["FastAPI wrappers for models", "Dockerizing ML containers", "Serverless ML Deployments"],
    "Cloud for ML": ["AWS SageMaker Pipelines", "GCP Vertex AI", "Azure ML Studio"],
    "Generative AI": ["Generative Adversarial Networks (GANs)", "Diffusion Models", "Variational Autoencoders"],
    "Large Language Models (LLMs)": ["Transformer Self-Attention", "Tokenizers & Vocab", "Context Windows"],
    "Prompt Engineering": ["Few-shot & Zero-shot Prompting", "Chain of Thought Prompting", "System vs User Prompts"],
    "Fine-Tuning": ["LoRA & QLoRA Parameter Efficient", "PEFT Framework Library"],
    "RAG (Retrieval-Augmented Generation)": ["Document Chunking strategies", "Embedding Documents", "Retrieval & Generation Flow"],
    "Vector Databases": ["Pinecone Database", "ChromaDB & FAISS", "PGVector PostgreSQL extension"],
    "AI Agents": ["LangChain & LangGraph Agents", "Tool Use & Function Calling", "ReAct loop pattern"],
    "AI System Design": ["LLM API Caching & Rate Limiting", "Vector Search Scale Optimization"],
    "ML Projects": ["End-to-End ML Pipeline Project", "Building ML Portfolios"]
  },
  "Core Subjects": {
    "OOPs": ["Classes & Objects", "Inheritance", "Polymorphism", "Abstraction", "Encapsulation"],
    "DBMS": ["SQL", "Joins", "Indexing", "Transactions", "Normalization"],
    "OS": ["Processes", "Threads", "Deadlocks", "Scheduling", "Memory Management"],
    "CN": ["OSI Model", "TCP/IP", "HTTP/HTTPS", "DNS", "Routing"],
    "System Design": ["Scalability", "Load Balancer", "Caching", "Databases", "Microservices"]
  }
};
